import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/useAuth';
import { useLanguage } from '@/contexts/LanguageContext';
import { useTranslations } from '@/lib/translations';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Plus, Edit, Trash2, Clock, Users, ChefHat, Star, Settings } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';

// Types
interface UserRecipe {
  id: number;
  userId: number;
  name: string;
  portion: string;
  ingredients: string[];
  instructions: string[];
  tips: string[];
  notes?: string;
  protein: number;
  calories: number;
  carbohydrates: number;
  fats: number;
  fiber: number;
  sugar: number;
  sodium: number;
  prepTime: number;
  cookTime: number;
  servings: number;
  mealTypes: string[];
  costEuros?: number;
  tags: string[];
  difficulty: string;

  createdAt: string;
  updatedAt: string;
  isActive: boolean;
}

// Form schema - nutrition fields will be auto-generated by AI
const recipeFormSchema = z.object({
  name: z.string().min(1, "Recipe name is required"),
  ingredients: z.array(z.string().min(1)).min(1, "At least one ingredient is required"),
  instructions: z.array(z.string().min(1)).min(1, "At least one instruction is required"),
  tips: z.array(z.string()).default([]),
  notes: z.string().optional(),
  prepTime: z.number().min(1, "Total time must be at least 1 minute"),
  servings: z.number().min(1, "Servings must be at least 1"),
  mealTypes: z.array(z.enum(["breakfast", "lunch", "dinner"])).min(1, "Select at least one meal type"),
  tags: z.array(z.string()).default([]),
});

type RecipeFormData = z.infer<typeof recipeFormSchema>;

export default function MyRecipes() {
  const { user } = useAuth();
  const { language } = useLanguage();
  const t = useTranslations(language);
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingRecipe, setEditingRecipe] = useState<UserRecipe | null>(null);
  const [useOnlyMyRecipes, setUseOnlyMyRecipes] = useState(false);
  const [ingredientCategories, setIngredientCategories] = useState<Record<number, { category: string; normalizedName: string }>>({});

  // Fetch user recipes
  const { data: recipes = [], isLoading, error: recipesError } = useQuery<UserRecipe[]>({
    queryKey: ['/api/user-recipes'],
    enabled: !!user,
  });

  // Fetch available dietary tags
  const { data: availableTags = [] } = useQuery<{ tag: string; count: number }[]>({
    queryKey: ['/api/admin/tags'],
    queryFn: () => fetch('/api/admin/tags').then(res => res.json()),
  });

  // Debug authentication
  React.useEffect(() => {
    console.log('Auth status:', { user: !!user, userId: user?.id });
    if (recipesError) {
      console.error('Recipes fetch error:', recipesError);
    }
  }, [user, recipesError]);

  // Fetch user profile to get recipe preference
  const { data: userProfile } = useQuery({
    queryKey: ['/api/users', user?.id, 'profile'],
    enabled: !!user?.id,
  });

  // Update local state when profile data loads
  React.useEffect(() => {
    if (userProfile && 'useOnlyMyRecipes' in userProfile && userProfile.useOnlyMyRecipes !== undefined) {
      setUseOnlyMyRecipes(userProfile.useOnlyMyRecipes);
    }
  }, [userProfile]);

  // Mutation to update recipe preference  
  const updatePreferenceMutation = useMutation({
    mutationFn: (useOnlyMyRecipes: boolean) => 
      apiRequest('PATCH', `/api/users/${user?.id}/profile`, { useOnlyMyRecipes }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/users', user?.id, 'profile'] });
      toast({ 
        title: useOnlyMyRecipes 
          ? "Now using ONLY your personal recipes" 
          : "Now using main recipe database",
        description: useOnlyMyRecipes 
          ? `Meal plans will use only your ${recipes.length} personal recipes`
          : "All meal plans will use the main curated recipe database"
      });
    },
    onError: (error: any) => {
      console.error('Preference update error:', error);
      // Revert the local state change since the server update failed
      setUseOnlyMyRecipes(!useOnlyMyRecipes);
      toast({ 
        title: "Failed to update preference", 
        description: error?.message || "Please try again",
        variant: "destructive" 
      });
    },
  });

  // Handle preference change
  const handlePreferenceChange = (checked: boolean) => {
    if (!user?.id) {
      console.error('No user ID found for preference update');
      return;
    }
    
    // Check minimum recipe requirement
    if (checked && recipes.length < 5) {
      toast({
        title: "Need more recipes",
        description: `You need at least 5 personal recipes to use only your own database. You currently have ${recipes.length}. Add ${5 - recipes.length} more recipe${5 - recipes.length > 1 ? 's' : ''} first.`,
        variant: "destructive"
      });
      return;
    }
    
    setUseOnlyMyRecipes(checked);
    updatePreferenceMutation.mutate(checked);
  };

  // Form setup
  const form = useForm<RecipeFormData>({
    resolver: zodResolver(recipeFormSchema),
    defaultValues: {
      name: '',
      ingredients: [''],
      instructions: [''],
      tips: [],
      notes: '',
      prepTime: 20,
      servings: 1,
      mealTypes: [],
      tags: [],
    },
  });

  // Analyze ingredients to get their categories
  const analyzeIngredients = async (ingredients: string[]) => {
    if (!ingredients || ingredients.length === 0) return;
    
    try {
      const response = await fetch('/api/analyze-ingredients', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ingredients })
      });
      
      if (response.ok) {
        const data = await response.json();
        const categories: Record<number, { category: string; normalizedName: string }> = {};
        data.analysis.forEach((item: {ingredient: string, category: string, normalizedIngredient?: string}, index: number) => {
          categories[index] = {
            category: item.category,
            normalizedName: item.normalizedIngredient || item.ingredient
          };
        });
        setIngredientCategories(categories);
      }
    } catch (error) {
      console.error('Error analyzing ingredients:', error);
    }
  };

  // Watch for ingredient changes and analyze them
  React.useEffect(() => {
    const subscription = form.watch((value, { name }) => {
      if (name?.startsWith('ingredients') && value.ingredients) {
        analyzeIngredients(value.ingredients as string[]);
      }
    });
    return () => subscription.unsubscribe();
  }, [form]);

  // Mutations
  const createMutation = useMutation({
    mutationFn: (data: RecipeFormData) => apiRequest('POST', '/api/user-recipes', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/user-recipes'] });
      setIsDialogOpen(false);
      setEditingRecipe(null);
      form.reset();
      toast({ title: "Recipe created successfully! Nutrition data auto-generated by AI." });
    },
    onError: (error: any) => {
      console.error('Recipe creation error:', error);
      toast({ 
        title: "Failed to create recipe", 
        description: error?.message || "Please try again",
        variant: "destructive" 
      });
    },
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: RecipeFormData }) => 
      apiRequest('PATCH', `/api/user-recipes/${id}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/user-recipes'] });
      setIsDialogOpen(false);
      setEditingRecipe(null);
      form.reset();
      toast({ title: "Recipe updated successfully! Nutrition data refreshed by AI." });
    },
    onError: () => {
      toast({ title: "Failed to update recipe", variant: "destructive" });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => apiRequest('DELETE', `/api/user-recipes/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/user-recipes'] });
      toast({ title: "Recipe deleted successfully!" });
    },
    onError: () => {
      toast({ title: "Failed to delete recipe", variant: "destructive" });
    },
  });

  // Form handlers
  const onSubmit = (data: RecipeFormData) => {
    console.log('Form submitted with data:', data);
    console.log('User authenticated:', !!user);
    
    if (editingRecipe) {
      updateMutation.mutate({ id: editingRecipe.id, data });
    } else {
      createMutation.mutate(data);
    }
  };

  const openEditDialog = (recipe: UserRecipe) => {
    setEditingRecipe(recipe);
    form.reset({
      name: recipe.name,
      ingredients: recipe.ingredients,
      instructions: recipe.instructions,
      tips: recipe.tips,
      notes: recipe.notes || '',
      prepTime: recipe.prepTime + (recipe.cookTime || 0), // Combine prep + cook time
      servings: recipe.servings,
      mealTypes: recipe.mealTypes as ("breakfast" | "lunch" | "dinner")[],
      tags: recipe.tags,
    });
    setIsDialogOpen(true);
  };

  const openCreateDialog = () => {
    setEditingRecipe(null);
    form.reset();
    setIsDialogOpen(true);
  };

  // Helper functions for form arrays
  const addIngredient = () => {
    const current = form.getValues('ingredients');
    form.setValue('ingredients', [...current, '']);
  };

  const removeIngredient = (index: number) => {
    const current = form.getValues('ingredients');
    form.setValue('ingredients', current.filter((_, i) => i !== index));
  };

  const addInstruction = () => {
    const current = form.getValues('instructions');
    form.setValue('instructions', [...current, '']);
  };

  const removeInstruction = (index: number) => {
    const current = form.getValues('instructions');
    form.setValue('instructions', current.filter((_, i) => i !== index));
  };

  const addTip = () => {
    const current = form.getValues('tips');
    form.setValue('tips', [...current, '']);
  };

  const removeTip = (index: number) => {
    const current = form.getValues('tips');
    form.setValue('tips', current.filter((_, i) => i !== index));
  };



  if (isLoading) {
    return <div className="p-6">{t.loadingRecipes}</div>;
  }

  return (
    <div className="container mx-auto p-6 max-w-6xl">
      <div className="mb-6">
        <div className="flex justify-between items-center mb-4">
          <div>
            <h1 className="text-3xl font-bold">{t.myRecipes}</h1>
            <p className="text-gray-600">{t.createPersonalRecipes}</p>
          </div>
          
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button 
                onClick={openCreateDialog} 
                className="flex items-center gap-2"
                disabled={!user}
              >
                <Plus className="h-4 w-4" />
                {t.addRecipe}
              </Button>
            </DialogTrigger>
            
            <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>{editingRecipe ? t.editRecipe : t.addNewRecipe}</DialogTitle>
              </DialogHeader>
              
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Basic Information */}
                    <div className="space-y-4">
                      <FormField
                        control={form.control}
                        name="name"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>{t.recipeName}</FormLabel>
                            <FormControl>
                              <Input placeholder={t.enterRecipeName} {...field} />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      
                      <FormField
                        control={form.control}
                        name="prepTime"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>{t.prepTime} (min)</FormLabel>
                            <FormControl>
                              <Input 
                                type="number" 
                                placeholder="Total prep + cooking time"
                                {...field} 
                                onChange={(e) => field.onChange(Number(e.target.value))}
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      
                      <FormField
                        control={form.control}
                        name="servings"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>{t.servings}</FormLabel>
                            <FormControl>
                              <Input 
                                type="number" 
                                {...field} 
                                onChange={(e) => field.onChange(Number(e.target.value))}
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      

                    </div>
                    
                    {/* Categories and Tags */}
                    <div className="space-y-4">
                      <FormField
                        control={form.control}
                        name="mealTypes"
                        render={() => (
                          <FormItem>
                            <FormLabel>{t.mealTypes}</FormLabel>
                            <div className="flex gap-4">
                              {['breakfast', 'lunch', 'dinner'].map((type) => (
                                <FormField
                                  key={type}
                                  control={form.control}
                                  name="mealTypes"
                                  render={({ field }) => {
                                    return (
                                      <FormItem
                                        key={type}
                                        className="flex flex-row items-start space-x-3 space-y-0"
                                      >
                                        <FormControl>
                                          <input
                                            type="checkbox"
                                            checked={field.value?.includes(type as "breakfast" | "lunch" | "dinner")}
                                            onChange={(checked) => {
                                              const mealType = type as "breakfast" | "lunch" | "dinner";
                                              return checked.target.checked
                                                ? field.onChange([...field.value, mealType])
                                                : field.onChange(
                                                    field.value?.filter(
                                                      (value) => value !== mealType
                                                    )
                                                  )
                                            }}
                                          />
                                        </FormControl>
                                        <FormLabel className="font-normal capitalize">
                                          {type}
                                        </FormLabel>
                                      </FormItem>
                                    )
                                  }}
                                />
                              ))}
                            </div>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      {/* Dietary Tags */}
                      <FormField
                        control={form.control}
                        name="tags"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>{t.dietaryTags || 'Dietary tags'}</FormLabel>
                            <FormControl>
                              <div className="flex flex-wrap gap-2 p-3 border rounded-md min-h-[100px]">
                                {availableTags.length === 0 ? (
                                  <p className="text-sm text-gray-400">Loading tags...</p>
                                ) : (
                                  availableTags.map(({ tag }) => {
                                    const isSelected = field.value?.includes(tag) || false;
                                    return (
                                      <Badge
                                        key={tag}
                                        variant={isSelected ? "default" : "secondary"}
                                        className={`cursor-pointer transition-colors ${
                                          isSelected 
                                            ? 'bg-emerald-500 hover:bg-emerald-600 text-white' 
                                            : 'hover:bg-gray-200'
                                        }`}
                                        onClick={() => {
                                          const currentTags = field.value || [];
                                          if (isSelected) {
                                            field.onChange(currentTags.filter(t => t !== tag));
                                          } else {
                                            field.onChange([...currentTags, tag]);
                                          }
                                        }}
                                      >
                                        {tag}
                                      </Badge>
                                    );
                                  })
                                )}
                              </div>
                            </FormControl>
                            <p className="text-xs text-gray-500 mt-1">
                              {t.clickTagsToSelect || 'Click on tags to select or deselect them'}
                            </p>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                      
                      <FormField
                        control={form.control}
                        name="notes"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>{t.additionalNotes}</FormLabel>
                            <FormControl>
                              <Textarea 
                                placeholder={t.enterNotes}
                                {...field} 
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                  </div>
                  
                  {/* AI Nutrition Notice */}
                  <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
                    <div className="flex items-start gap-2">
                      <div className="text-blue-600 mt-0.5">🤖</div>
                      <div>
                        <h4 className="font-medium text-blue-900 text-sm">{t.aiNutritionAnalysis}</h4>
                        <p className="text-blue-700 text-xs mt-1">
                          {t.nutritionAutoCalculated}
                        </p>
                      </div>
                    </div>
                  </div>
                  
                  {/* Ingredients - Two Column Layout */}
                  <div>
                    <FormLabel className="text-base font-medium">{t.ingredients}</FormLabel>
                    <div className="text-sm text-gray-600 mb-3">
                      Enter ingredients with quantities (e.g., "200g quinoa"). Mappings show how they'll appear on shopping lists.
                    </div>
                    <div className="space-y-2 mt-2">
                      {/* Header Row */}
                      <div className="grid grid-cols-2 gap-2 text-xs font-medium text-gray-600 px-2 pb-1 border-b">
                        <div>Recipe ingredient</div>
                        <div>Shopping list mapping</div>
                      </div>
                      
                      {form.watch('ingredients').map((_, index) => (
                        <div key={index} className="flex gap-2 items-start">
                          <div className="grid grid-cols-2 gap-2 flex-1">
                            <FormField
                              control={form.control}
                              name={`ingredients.${index}`}
                              render={({ field }) => (
                                <FormItem>
                                  <FormControl>
                                    <Input 
                                      placeholder={t.enterIngredient}
                                      {...field}
                                      className="w-full"
                                    />
                                  </FormControl>
                                  <FormMessage />
                                </FormItem>
                              )}
                            />
                            <div className="flex items-center gap-2">
                              <div className="flex-1 px-3 py-2 bg-gray-50 border border-gray-200 rounded-md text-sm">
                                {ingredientCategories[index] ? (
                                  <div>
                                    <div className="font-medium text-gray-900">
                                      {ingredientCategories[index].normalizedName || 'No mapping'}
                                    </div>
                                    <div className="text-xs text-gray-500">
                                      {ingredientCategories[index].category}
                                    </div>
                                  </div>
                                ) : (
                                  <span className="text-gray-400 text-xs">Analyzing...</span>
                                )}
                              </div>
                            </div>
                          </div>
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeIngredient(index)}
                            disabled={form.watch('ingredients').length <= 1}
                            data-testid={`remove-ingredient-${index}`}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={addIngredient}
                        className="mt-2"
                      >
                        <Plus className="h-4 w-4 mr-2" />
                        {t.addIngredientStep}
                      </Button>
                    </div>
                  </div>
                  
                  {/* Instructions */}
                  <div>
                    <FormLabel className="text-base font-medium">{t.instructions}</FormLabel>
                    <div className="space-y-2 mt-2">
                      {form.watch('instructions').map((_, index) => (
                        <div key={index} className="flex gap-2">
                          <div className="flex-shrink-0 w-8 h-8 bg-gray-100 rounded-full flex items-center justify-center text-xs font-medium mt-1">
                            {index + 1}
                          </div>
                          <FormField
                            control={form.control}
                            name={`instructions.${index}`}
                            render={({ field }) => (
                              <FormItem className="flex-1">
                                <FormControl>
                                  <Textarea 
                                    placeholder={t.enterInstruction}
                                    {...field} 
                                  />
                                </FormControl>
                                <FormMessage />
                              </FormItem>
                            )}
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeInstruction(index)}
                            disabled={form.watch('instructions').length <= 1}
                            className="mt-1"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={addInstruction}
                        className="mt-2"
                      >
                        <Plus className="h-4 w-4 mr-2" />
                        {t.addInstructionStep}
                      </Button>
                    </div>
                  </div>
                  
                  {/* Tips (optional) */}
                  <div>
                    <FormLabel className="text-base font-medium">{t.tips} {t.optional}</FormLabel>
                    <div className="space-y-2 mt-2">
                      {form.watch('tips').map((_, index) => (
                        <div key={index} className="flex gap-2">
                          <FormField
                            control={form.control}
                            name={`tips.${index}`}
                            render={({ field }) => (
                              <FormItem className="flex-1">
                                <FormControl>
                                  <Input 
                                    placeholder={t.enterTip}
                                    {...field} 
                                  />
                                </FormControl>
                                <FormMessage />
                              </FormItem>
                            )}
                          />
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => removeTip(index)}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={addTip}
                        className="mt-2"
                      >
                        <Plus className="h-4 w-4 mr-2" />
                        {t.addTipStep}
                      </Button>
                    </div>
                  </div>
                  
                  {/* Submit Buttons */}
                  <div className="flex justify-end gap-3 pt-4">
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => {
                        setIsDialogOpen(false);
                        setEditingRecipe(null);
                        form.reset();
                      }}
                    >
                      {t.cancel}
                    </Button>
                    <Button
                      type="submit"
                      disabled={createMutation.isPending || updateMutation.isPending}
                    >
                      {createMutation.isPending || updateMutation.isPending ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                          {editingRecipe ? t.updatingRecipe : t.creatingRecipe}
                        </>
                      ) : (
                        <>
                          {editingRecipe ? t.editRecipe : t.addRecipe}
                        </>
                      )}
                    </Button>
                  </div>
                </form>
              </Form>
            </DialogContent>
          </Dialog>
        </div>
        
        {/* Recipe Source Preference */}
        <div className="p-4 bg-gray-50 rounded-lg border">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center space-x-2">
              <Settings className="h-4 w-4 text-gray-600" />
              <Label htmlFor="recipe-source" className="text-sm font-medium">
                {t.useOnlyMyRecipes}
              </Label>
            </div>
            <Switch
              id="recipe-source"
              checked={useOnlyMyRecipes}
              onCheckedChange={handlePreferenceChange}
              disabled={updatePreferenceMutation.isPending || !user || recipes.length < 5}
            />
          </div>
          <p className="text-xs text-gray-500 mb-2">
            When enabled, meal plans will use ONLY your personal recipes (no main database). You need at least 5 recipes to enable this.
          </p>
          <div className="text-xs space-y-1">
            <div>
              {useOnlyMyRecipes 
                ? <span className="text-emerald-600 bg-emerald-100 px-2 py-1 rounded">✓ Using ONLY your {recipes.length} personal recipes</span>
                : <span className="text-gray-600 bg-gray-100 px-2 py-1 rounded">Using main recipe database</span>
              }
            </div>
            {recipes.length < 5 && (
              <div className="text-amber-600 bg-amber-50 px-2 py-1 rounded border border-amber-200">
                Need {5 - recipes.length} more recipe{5 - recipes.length > 1 ? 's' : ''} to enable personal database
              </div>
            )}
          </div>
        </div>
        
        {/* Nutrition Enhancement Tips */}
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <div className="flex items-start gap-3">
            <div className="text-blue-600 mt-0.5">💡</div>
            <div>
              <h3 className="font-medium text-blue-900 text-sm mb-2">Boost Your Recipe Nutrition</h3>
              <div className="text-blue-700 text-sm space-y-2">
                <div>
                  <span className="font-medium">Add More Protein:</span> Hemp hearts (10g/30ml), protein powder (20-25g), Greek yogurt, quinoa, lentils, chickpeas, tofu, nuts & seeds
                </div>
                <div>
                  <span className="font-medium">Increase Fiber:</span> Chia seeds (5g/15ml), ground flaxseeds, beans, oats, berries, vegetables, whole grains, ripe avocado
                </div>
                <div>
                  <span className="font-medium">Easy Swaps:</span> Replace white rice → brown rice/quinoa, regular pasta → lentil pasta, flour → almond/oat flour blend
                </div>
              </div>
            </div>
          </div>
        </div>
        
        {/* Construction Notice */}
        <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg">
          <div className="flex items-start gap-3">
            <div className="text-amber-600 mt-0.5">🚧</div>
            <div>
              <h3 className="font-medium text-amber-900 text-sm">Fridge Integration Under Construction</h3>
              <p className="text-amber-700 text-sm mt-1">
                We're working on connecting your recipes with the fridge inventory system to suggest meals based on ingredients you already have. This feature will be available soon!
              </p>
            </div>
          </div>
        </div>
      </div>

      {recipes.length === 0 ? (
        <div className="text-center py-12">
          <ChefHat className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">{t.noRecipesYet}</h3>
          <p className="text-gray-500 mb-4">{t.startAddingRecipes}</p>
          <Button 
            onClick={openCreateDialog} 
            className="flex items-center gap-2 mx-auto"
            disabled={!user}
          >
            <Plus className="h-4 w-4" />
            {t.addRecipe}
          </Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {recipes.map((recipe) => (
            <Card key={recipe.id} className="overflow-hidden hover:shadow-lg transition-shadow">
              <CardHeader className="pb-3">
                <div className="flex justify-between items-start">
                  <CardTitle className="text-lg leading-tight">{recipe.name}</CardTitle>
                  <div className="flex gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => openEditDialog(recipe)}
                      className="h-8 w-8 p-0"
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => deleteMutation.mutate(recipe.id)}
                      className="h-8 w-8 p-0 text-red-600 hover:text-red-700"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div className="flex items-center gap-2 text-sm text-gray-600">
                  <span>{(() => {
                    if (!recipe.portion) return '1';
                    const numberMatch = recipe.portion.match(/(\d+(?:\.\d+)?)/);
                    return numberMatch ? numberMatch[1] : '1';
                  })()} servings</span>
                </div>
              </CardHeader>
              
              <CardContent>
                <div className="space-y-3">
                  <div className="flex flex-wrap gap-2">
                    {recipe.mealTypes.map((type) => (
                      <span key={type} className="px-2 py-1 bg-blue-50 text-blue-700 text-xs rounded-full capitalize">
                        {type}
                      </span>
                    ))}
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="font-medium">Protein:</span> {recipe.protein}g
                    </div>
                    <div>
                      <span className="font-medium">Calories:</span> {recipe.calories}
                    </div>
                  </div>
                  
                  {recipe.notes && (
                    <p className="text-gray-500 text-xs italic line-clamp-2">{recipe.notes}</p>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Dialog is already handled above */}
    </div>
  );
}